<?xml version='1.0' encoding='ISO-8859-1'?>
<!DOCTYPE test PUBLIC "-//Software Carpentry//QMTest Test V0.1//EN" "http://www.software-carpentry.com/qm/xml/test.dtd">
<test>
 <class>python.ExceptionTest</class>
 <argument name='source'>
  <text>
import qm.graph
nodes = [1, 2, 4, 5, 6, 7, 8]
edges = {
    1: [2], 
    2: [3], 
    3: [], 
    4: [6, 7], 
    5: [], 
    6: [5, 3], 
    7: [5], 
    8: [1, 4]
    }
qm.graph.topological_sort(nodes, edges, 1)
</text>
 </argument>
 <argument name='exception_class'>
  <text>ValueError</text>
 </argument>
 <argument name='exception_argument'>
  <text>'predecessor not in nodes'</text>
 </argument>
</test>
<!--
  Local Variables:
  mode: xml
  indent-tabs-mode: nil
  fill-column: 72
  sgml-indent-step: 1
  End:
-->
